spring:
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://test:q1w2e3@localhost:27017/
      database: test
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: test
      password: q1w2e3
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: test
