spring:
  security:
    cors:
      allowed-headers:
        - Authorization
        - Content-Type
      allowed-methods: GET,POST,PATCH,DELETE,OPTIONS
      allow-credentials: false
      allowed-origins:
        - "*"