spring:
  data:
    mongodb:
      connection-pool:
        min-size: 10
        max-size: 20
        max-connection-life-time: 30s
        max-connection-idle-time: 30s
        max-wait-time: 10s
      authentication-database: admin